### ISSUE TITLE
Add country population from World Bank

### ISSUE THREAD

**Issue by JustinLoye** [InternetHealthReport/internet-yellow-pages#129]
**Explain the dataset you want to add and how it would contribute to the Internet Yellow Pages.**
It could be useful to have the countries' population. For example the ranking ihr.country_dependency gives the relative population coverage of eyeball networks per country, but does not indicate the actual population value.  

World Bank seems to be the authoritative data source. 

**Provide the name of the organization providing the data and the url to the dataset**
- Org name: World Bank
- URL: http://api.worldbank.org/v2/country/all/indicator/SP.POP.TOTL?per_page=400&mrv=1&format=json

**If possible describe how you would like to model the dataset in the Yellow Pages**
Since there is only one value from one dataset per country, I suggest adding it as a node property

- What is the label/type of the nodes used by this dataset?
(n: Country)

**Comment by m-appel** [comment]
Although it is intuitive to want to add it as a node property, I would propose we add it as a `POPULATION` relationship to some node instead.

The main reason is that we could not track the source of the data like we normally do (the `reference_*` properties only exist for relationships). This would be fine if the population would be a de-facto value (like the country name we add in [`country_information`](https://github.com/InternetHealthReport/internet-yellow-pages/blob/main/iyp/post/country_information.py)), but it is not.

Another reason would be that if we ever wanted to add a second source for population estimates (I don't think we will, but oh well...), we could not do so.

The only question is how we label the node we connect the relationship with. I'd propose to be generic and just call it `Estimate`, with a `name` property.
We could be more specific, like `PopulationEstimate`, but I don't see a reason for this, since we have the `POPULATION` already in the relationship. And we could reuse `Estimate` for other things in the future. Opinions @romain-fontugne?

```cypher
(:Country)-[:POPULATION {value: 123}]->(:Estimate {name: 'World Bank Population Estimate')
```
