### ISSUE TITLE
Bug/JSONDecoder Error in 'iyp.crawlers.ihr.country_dependency' Module

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/internet-yellow-pages#79]
**Describe the bug**
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 401815 (char 401814) in `iyp.crawlers.ihr.country_dependency` module

**To Reproduce**
Please check `iyp-2023-12-01.log`:
https://exp1.iijlab.net/wip/iyp/dumps/2023/12/01/iyp-2023-12-01.log

**Screenshots**
<img width="1215" alt="Screenshot 2023-12-12 at 8 49 03 AM" src="https://github.com/InternetHealthReport/internet-yellow-pages/assets/69568555/010d3cba-d7a6-40d6-b10c-c221a15c4e88">

**Comment by m-appel** [comment]
Hi, thanks for looking at the logs :)
However, we actually do not need issues based on errors from the logs, since we already check them every week. Sometimes crawlers fail due to connectivity errors (like in this case) and just need to be rerun.
Romain added a line at the bottom
> 2023-12-06 00:00 Romain: manually reruned ihr_dependency

so this is already addressed.

But, I will take this opportunity and update the Bug Report issue template to highlight that we don't need reports based on the log.

Thanks

**Comment by romain-fontugne** [comment]
thank you both :)
