### ISSUE TITLE
Bug: Lack of Idempotence in `batch_add_links` Method Causes Duplicate Relationship Links

### ISSUE THREAD

**Issue by mohamedawnallah** [InternetHealthReport/internet-yellow-pages#95]
### Bug Description
The [`batch_add_links`](https://github.com/InternetHealthReport/internet-yellow-pages/blob/a6abff3e8131d477b739b266c3d6025b578daf11/iyp/__init__.py#L453-L492) function lacks idempotence, causing duplicate relationship links associated with the crawler every time the crawler pipeline is re-run.

### Steps to Reproduce Locally:
1. Choose a crawler (e.g., `atlas_probes.py`), its associated links (`AtlasProbe` Node Label, and `ASSIGNED` relationship).
2. Ensure deletion of all `AtlasProbe` Node Label and `ASSIGNED` relationships before detecting the bug unless using a fresh neo4j database server.
3. Run `atlas_probes.py` to load the database.
4. After data loading, execute the query:

    ```cql
    MATCH (probe:AtlasProbe)<-[:ASSIGNED]-(ip:IP)
    WITH probe, ip, COUNT(*) AS linkCount
    WHERE linkCount > 1
    RETURN ip, probe, linkCount
    LIMIT 25
    ```
5. No duplicate links should appear.
6. Rerun the pipeline; observe relationship links getting duplicated, similar to the first screenshot.

### Reproducing in Production:
1. Access the IYP Production Neo4j Server: [Link to Server](https://iyp.iijlab.net/iyp/browser/?dbms=iyp-bolt.iijlab.net:443).
2. Run the query:

    ```cql
    MATCH (asn:AS)-[:COUNTRY]->(country:Country)
    WITH asn, country, COUNT(*) AS linkCount
    WHERE linkCount > 1
    RETURN asn, country, linkCount
    LIMIT 25 
    ```
3. Observe duplicated relationship links, similar to the last screenshot.

### Expected Behavior
The relationship links should not duplicate on re-running the data pipeline. This duplication significantly impacts database dump size and query performance.

#### Local Development Neo4j Server:
- `ASSIGNED` relationships duplicated twice on running the data pipeline twice between `IP` -> `AtlasProbe` Node Labels.
![Local Development Screenshot](https://github.com/InternetHealthReport/internet-yellow-pages/assets/69568555/e231fedd-12c0-41c6-8502-ffe0e46fb7fe)

#### Production Neo4j Server:
- `COUNTRY` relationships duplicated between `AS` -> `COUNTRY` Node Labels.
![Production Screenshot](https://github.com/InternetHealthReport/internet-yellow-pages/assets/69568555/7e80b576-804f-4df4-b79d-5922d5ef5ce6)

**Comment by romain-fontugne** [comment]
This is not a bug :smiley: 

The default behavior for this function is to add links even if a link between two nodes already exists (this is really the equivalent of CREATE in neo4j). You can use the `action='merge'` parameter if you want to merge with existing links but in principles we don't use that option.

We made the design choice that each dataset will add a different set of links, so we can confidently dissociate data from different datasets. In the example you gave for the production server, each of the link `(:AS)--(:Country)` corresponds to a different source dataset. See the `reference_org`, `reference_name`, and `reference_url` properties on the links. This may looks weird when using the web interface but it is actually very useful when we do data analysis and we want to cherry pick certain datasets. Also some datasets contains multiple links between two nodes (e.g. bgpkit's as2rel) with different properties on the links.

Our data pipeline is not intended to be executed multiple times. Image a datapipeline as one snapshot. We usually don't rerun a single crawler. If I have to re-un a crawler I usually run 
```
DELETE ()-[{reference_name: 'crawler_name_here'}]-()
```
before re-running it. Sorry this is not documented because we want to avoid re-running crawlers. It is ok when developing but we should keep in mind that re-running crawlers is a source of troubles for other things (node deduplication, isolated nodes, properties overwriting, outdated links, etc...). Maybe we could automate this using `reference_name` and `reference_date` properties on the links but I think this goes beyond this issue.

**Comment by mohamedawnallah** [comment]
Yes that makes much sense. Thanks for explaining the design choice in detail 🙏
